BASE_URL = "https://contactapp-telran-backend.herokuapp.com"
API_VERSION = "/v1"
REGISTRATION_URL =  "/user/registration/usernamepassword"
LOGIN_URL = "/user/login/usernamepassword"
ADD_CONTACT_URL = "/contacts"
TEST_EMAIL = "uriah_gislason86@gmail.com"
TEST_PASSWORD = "hggfdR876598@"